# Form implementation generated from reading ui file 'grammatica.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(904, 969)
        Form.setStyleSheet("QWidget {\n"
"    background-image: url(\"C:/Users/harri/Desktop/Nederlands app/images/arkaplan_resmi.webp\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"}\n"
"/* Başlık Frame\'i */\n"
"QFrame {\n"
"    background: transparent; /* Şeffaf bırak */\n"
"    border: none;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #f0f8ff; /* Açık mavi tonunda arka plan */\n"
"    border: 2px solid #4682b4; /* Hafif koyu mavi çerçeve */\n"
"    border-radius: 8px; /* Köşeleri yuvarlak yap */\n"
"    padding: 6px; /* İçeride boşluk bırak */\n"
"    font-size: 14px;\n"
"    color: #333; /* Yazı rengi */\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"    background: transparent; \n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #31857F;\n"
"}\n"
"\n"
"/* Kullanıcı Girişi Frame\'i */\n"
"QFrame#inputFrame {\n"
"    background: transparent; \n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #f0f5f9;\n"
"    border: 2px solid #5EAAA8;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 16px;\n"
"    color: #333;\n"
"}\n"
"\n"
"/* Butonların Bulunduğu Frame */\n"
"QFrame#progressFrame {\n"
"    background: transparent;\n"
"}\n"
"QPushButton {\n"
"    background-color: #5EAAA8; /* Normal buton rengi */\n"
"    color: #F4D03F; /* Sarımsı yazı rengi */\n"
"    border-radius: 10px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    padding: 8px 15px;\n"
"    font-size: 20px;\n"
"    border: 2px solid #31857F;\n"
"}\n"
"\n"
"/* Mouse ile üzerine gelince */\n"
"QPushButton:hover {\n"
"    background-color: #76C7C0; /* Daha açık yeşil */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Tıklayınca */\n"
"QPushButton:pressed {\n"
"    background-color: #EAF4F4; /* Açık renk */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Butonun şeffaf olmasını önlemek için */\n"
"QPushButton:!disabled {\n"
"    background: #5EAAA8; \n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(200, 10, 481, 71))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \"Comic Sans MS\"; /* Daha eğlenceli ve oyunumsu bir font */\n"
"    font-size: 25pt; /* Boyutu biraz daha artırdık, daha dikkat çekici olsun */\n"
"    font-weight: bold; /* Kalın yazı (eğlenceli duruşu koruyor) */\n"
"    color: #F57C00; /* Daha koyu turuncu ton (orijinal #FF9800’dan daha derin) */\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox_gramerSec = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_gramerSec.setGeometry(QtCore.QRect(40, 160, 361, 31))
        self.comboBox_gramerSec.setObjectName("comboBox_gramerSec")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 115, 301, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_tukce = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_tukce.setGeometry(QtCore.QRect(50, 296, 791, 41))
        self.lineEdit_tukce.setObjectName("lineEdit_tukce")
        self.lineEdit_hollandaca = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_hollandaca.setGeometry(QtCore.QRect(50, 355, 791, 41))
        self.lineEdit_hollandaca.setObjectName("lineEdit_hollandaca")
        self.pushButton_kaydet = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_kaydet.setGeometry(QtCore.QRect(50, 410, 141, 51))
        self.pushButton_kaydet.setObjectName("pushButton_kaydet")
        self.pushButton_sil = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_sil.setGeometry(QtCore.QRect(370, 410, 151, 51))
        self.pushButton_sil.setObjectName("pushButton_sil")
        self.pushButton_duzenle = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_duzenle.setGeometry(QtCore.QRect(681, 410, 161, 51))
        self.pushButton_duzenle.setObjectName("pushButton_duzenle")
        self.textEdit_aciklama = QtWidgets.QTextEdit(parent=self.frame)
        self.textEdit_aciklama.setGeometry(QtCore.QRect(420, 150, 421, 111))
        self.textEdit_aciklama.setStyleSheet("#textEdit_aciklama {\n"
"    background-color: #f0f5f9; /* Açık sarı tonu (tablodaki gibi) */\n"
"    border: 2px solid #5EAAA8; /* Çerçeve */\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"")
        self.textEdit_aciklama.setReadOnly(True)
        self.textEdit_aciklama.setObjectName("textEdit_aciklama")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(430, 110, 121, 31))
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_ara = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_ara.setGeometry(QtCore.QRect(750, 20, 93, 41))
        self.pushButton_ara.setObjectName("pushButton_ara")
        self.lineEdit_metinAra = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_metinAra.setGeometry(QtCore.QRect(40, 23, 681, 41))
        self.lineEdit_metinAra.setObjectName("lineEdit_metinAra")
        self.pushButton_geriDon = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_geriDon.setGeometry(QtCore.QRect(552, 407, 291, 51))
        self.pushButton_geriDon.setObjectName("pushButton_geriDon")
        self.tableWidget_grammatica = QtWidgets.QTableWidget(parent=self.frame_2)
        self.tableWidget_grammatica.setGeometry(QtCore.QRect(40, 90, 801, 301))
        self.tableWidget_grammatica.setStyleSheet("background-color: rgb(246, 255, 205);")
        self.tableWidget_grammatica.setObjectName("tableWidget_grammatica")
        self.tableWidget_grammatica.setColumnCount(0)
        self.tableWidget_grammatica.setRowCount(0)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Grammatica"))
        self.label.setText(_translate("Form", "Grammaticapraktijk"))
        self.label_2.setText(_translate("Form", "Kies een grammaticaonderwerp"))
        self.lineEdit_tukce.setPlaceholderText(_translate("Form", "Voer een zin in het Turks in"))
        self.lineEdit_hollandaca.setPlaceholderText(_translate("Form", "Voer een zin in het Nederlands in"))
        self.pushButton_kaydet.setText(_translate("Form", "Opslaan"))
        self.pushButton_sil.setText(_translate("Form", "Verwijderen"))
        self.pushButton_duzenle.setText(_translate("Form", "Wijzigen"))
        self.label_6.setText(_translate("Form", "Beschrijving"))
        self.pushButton_ara.setText(_translate("Form", "Zoek"))
        self.pushButton_geriDon.setText(_translate("Form", "Terug naar startpagina"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
