# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Inloggen(object):
    def setupUi(self, Inloggen):
        Inloggen.setObjectName("Inloggen")
        Inloggen.resize(400, 600)
        Inloggen.setMinimumSize(QtCore.QSize(400, 600))
        Inloggen.setMaximumSize(QtCore.QSize(400, 600))
        Inloggen.setStyleSheet("QWidget {\n"
"    background-image: url(\"C:/Users/harri/Desktop/Nederlands app/images/arkaplan_resmi.webp\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: transparent; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #31857F;\n"
"}\n"
"\n"
"\n"
"QLineEdit {\n"
"    background-color: #f0f5f9;\n"
"    border: 2px solid #5EAAA8;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #5EAAA8; /* Normal buton rengi */\n"
"    color: #F4D03F; /* Sarımsı yazı rengi */\n"
"    border-radius: 10px;\n"
"    padding: 8px 15px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    font-size: 17px;\n"
"    border: 2px solid #31857F;\n"
"}\n"
"\n"
"/* Mouse ile üzerine gelince */\n"
"QPushButton:hover {\n"
"    background-color: #76C7C0; /* Daha açık yeşil */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Tıklayınca */\n"
"QPushButton:pressed {\n"
"    background-color: #EAF4F4; /* Açık renk */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Butonun şeffaf olmasını önlemek için */\n"
"QPushButton:!disabled {\n"
"    background: #5EAAA8; \n"
"}\n"
"")
        self.label_3 = QtWidgets.QLabel(parent=Inloggen)
        self.label_3.setGeometry(QtCore.QRect(70, 60, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    font-family: \"Comic Sans MS\"; /* Daha eğlenceli ve oyunumsu bir font */\n"
"    font-size: 25pt; /* Boyutu biraz daha artırdık, daha dikkat çekici olsun */\n"
"    font-weight: bold; /* Kalın yazı (eğlenceli duruşu koruyor) */\n"
"    color: #F57C00; /* Daha koyu turuncu ton (orijinal #FF9800’dan daha derin) */\n"
"}")
        self.label_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_registreren = QtWidgets.QPushButton(parent=Inloggen)
        self.pushButton_registreren.setGeometry(QtCore.QRect(130, 490, 151, 51))
        self.pushButton_registreren.setStyleSheet("")
        self.pushButton_registreren.setObjectName("pushButton_registreren")
        self.lineEdit_wachtwoord = QtWidgets.QLineEdit(parent=Inloggen)
        self.lineEdit_wachtwoord.setGeometry(QtCore.QRect(100, 319, 211, 41))
        self.lineEdit_wachtwoord.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_wachtwoord.setObjectName("lineEdit_wachtwoord")
        self.label = QtWidgets.QLabel(parent=Inloggen)
        self.label.setGeometry(QtCore.QRect(120, 184, 171, 31))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \"Comic Sans MS\"; /* Daha eğlenceli ve oyunumsu bir font */\n"
"    font-size: 13pt; /* Boyutu biraz daha artırdık, daha dikkat çekici olsun */\n"
"    font-weight: bold; /* Kalın yazı (eğlenceli duruşu koruyor) */\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit_gebruikersNaam = QtWidgets.QLineEdit(parent=Inloggen)
        self.lineEdit_gebruikersNaam.setGeometry(QtCore.QRect(100, 220, 211, 41))
        self.lineEdit_gebruikersNaam.setObjectName("lineEdit_gebruikersNaam")
        self.label_2 = QtWidgets.QLabel(parent=Inloggen)
        self.label_2.setGeometry(QtCore.QRect(118, 283, 151, 31))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-family: \"Comic Sans MS\"; /* Daha eğlenceli ve oyunumsu bir font */\n"
"    font-size: 13pt; /* Boyutu biraz daha artırdık, daha dikkat çekici olsun */\n"
"    font-weight: bold; /* Kalın yazı (eğlenceli duruşu koruyor) */\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton_inloggen = QtWidgets.QPushButton(parent=Inloggen)
        self.pushButton_inloggen.setGeometry(QtCore.QRect(144, 410, 121, 51))
        self.pushButton_inloggen.setStyleSheet("")
        self.pushButton_inloggen.setObjectName("pushButton_inloggen")

        self.retranslateUi(Inloggen)
        QtCore.QMetaObject.connectSlotsByName(Inloggen)

    def retranslateUi(self, Inloggen):
        _translate = QtCore.QCoreApplication.translate
        Inloggen.setWindowTitle(_translate("Inloggen", "Inloggen"))
        self.label_3.setText(_translate("Inloggen", "Inloggen"))
        self.pushButton_registreren.setText(_translate("Inloggen", "Registreren"))
        self.label.setText(_translate("Inloggen", "Gebruikersnaam"))
        self.label_2.setText(_translate("Inloggen", "Wachtwoord"))
        self.pushButton_inloggen.setText(_translate("Inloggen", "Inloggen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inloggen = QtWidgets.QWidget()
    ui = Ui_Inloggen()
    ui.setupUi(Inloggen)
    Inloggen.show()
    sys.exit(app.exec())
