# Form implementation generated from reading ui file 'voorkeurenpagina.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_voorkeurenpagina(object):
    def setupUi(self, voorkeurenpagina):
        voorkeurenpagina.setObjectName("voorkeurenpagina")
        voorkeurenpagina.resize(750, 650)
        voorkeurenpagina.setMaximumSize(QtCore.QSize(750, 650))
        voorkeurenpagina.setStyleSheet("QWidget {\n"
"    background-image: url(\"C:/Users/harri/Desktop/Nederlands app/images/arkaplan_resmi.webp\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: transparent; \n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #31857F;\n"
"}\n"
"\n"
"\n"
"\n"
"QLineEdit {\n"
"    background-color: #f0f5f9;\n"
"    border: 2px solid #5EAAA8;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 16px;\n"
"    color: #333;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background-color: #5EAAA8; /* Normal buton rengi */\n"
"    color: #F4D03F; /* Sarımsı yazı rengi */\n"
"    border-radius: 10px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    padding: 8px 15px;\n"
"    font-size: 20px;\n"
"    border: 2px solid #31857F;\n"
"}\n"
"\n"
"/* Mouse ile üzerine gelince */\n"
"QPushButton:hover {\n"
"    background-color: #76C7C0; /* Daha açık yeşil */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Tıklayınca */\n"
"QPushButton:pressed {\n"
"    background-color: #EAF4F4; /* Açık renk */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Butonun şeffaf olmasını önlemek için */\n"
"QPushButton:!disabled {\n"
"    background: #5EAAA8; \n"
"}\n"
"")
        self.progressBar = QtWidgets.QProgressBar(parent=voorkeurenpagina)
        self.progressBar.setGeometry(QtCore.QRect(190, 593, 401, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #666; /* Koyu gri kenarlık */\n"
"    border-radius: 5px; /* Hafif yuvarlak köşeler */\n"
"    background-color: #F5F5F5; /* Açık gri arka plan */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #FF9800; /* Turuncu dolgu */\n"
"    border-radius: 5px; /* Yuvarlak dolgu köşeleri */\n"
"    width: 10px;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_uitloggen = QtWidgets.QPushButton(parent=voorkeurenpagina)
        self.pushButton_uitloggen.setGeometry(QtCore.QRect(670, 14, 61, 51))
        self.pushButton_uitloggen.setStyleSheet("QPushButton {\n"
"background: transparent; \n"
"}")
        self.pushButton_uitloggen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_uitloggen.setIcon(icon)
        self.pushButton_uitloggen.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_uitloggen.setObjectName("pushButton_uitloggen")
        self.pushButton_woordstudie = QtWidgets.QPushButton(parent=voorkeurenpagina)
        self.pushButton_woordstudie.setGeometry(QtCore.QRect(100, 213, 251, 101))
        self.pushButton_woordstudie.setObjectName("pushButton_woordstudie")
        self.label_welkom_userName = QtWidgets.QLabel(parent=voorkeurenpagina)
        self.label_welkom_userName.setGeometry(QtCore.QRect(584, 17, 71, 31))
        self.label_welkom_userName.setText("")
        self.label_welkom_userName.setObjectName("label_welkom_userName")
        self.pushButton_grammatica = QtWidgets.QPushButton(parent=voorkeurenpagina)
        self.pushButton_grammatica.setGeometry(QtCore.QRect(400, 213, 261, 101))
        self.pushButton_grammatica.setObjectName("pushButton_grammatica")
        self.label_3 = QtWidgets.QLabel(parent=voorkeurenpagina)
        self.label_3.setGeometry(QtCore.QRect(503, 17, 81, 31))
        self.label_3.setStyleSheet("font-family: \"Comic Sans MS\";")
        self.label_3.setObjectName("label_3")
        self.title = QtWidgets.QLabel(parent=voorkeurenpagina)
        self.title.setGeometry(QtCore.QRect(160, 97, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel#title {\n"
"    font-family: \"Comic Sans MS\"; /* Daha eğlenceli ve oyunumsu bir font */\n"
"    font-size: 25pt; /* Boyutu biraz daha artırdık, daha dikkat çekici olsun */\n"
"    font-weight: bold; /* Kalın yazı (eğlenceli duruşu koruyor) */\n"
"    color: #F57C00; /* Daha koyu turuncu ton (orijinal #FF9800’dan daha derin) */\n"
"}")
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.pushButton_maakQuiz = QtWidgets.QPushButton(parent=voorkeurenpagina)
        self.pushButton_maakQuiz.setGeometry(QtCore.QRect(100, 350, 251, 91))
        self.pushButton_maakQuiz.setObjectName("pushButton_maakQuiz")
        self.pushButton_voortgangBekijken = QtWidgets.QPushButton(parent=voorkeurenpagina)
        self.pushButton_voortgangBekijken.setGeometry(QtCore.QRect(400, 350, 261, 91))
        self.pushButton_voortgangBekijken.setObjectName("pushButton_voortgangBekijken")
        self.label = QtWidgets.QLabel(parent=voorkeurenpagina)
        self.label.setGeometry(QtCore.QRect(190, 553, 141, 31))
        self.label.setObjectName("label")

        self.retranslateUi(voorkeurenpagina)
        QtCore.QMetaObject.connectSlotsByName(voorkeurenpagina)

    def retranslateUi(self, voorkeurenpagina):
        _translate = QtCore.QCoreApplication.translate
        voorkeurenpagina.setWindowTitle(_translate("voorkeurenpagina", "Voorkeurenpagina"))
        self.pushButton_woordstudie.setText(_translate("voorkeurenpagina", "Woordstudie"))
        self.pushButton_grammatica.setText(_translate("voorkeurenpagina", "Bestudeer grammatica"))
        self.label_3.setText(_translate("voorkeurenpagina", "Welkom,"))
        self.title.setText(_translate("voorkeurenpagina", "Je Nederlandse reis "))
        self.pushButton_maakQuiz.setText(_translate("voorkeurenpagina", "Maak Quiz"))
        self.pushButton_voortgangBekijken.setText(_translate("voorkeurenpagina", "Mijn Voortgang Bekijken"))
        self.label.setText(_translate("voorkeurenpagina", "Uw voortgang"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    voorkeurenpagina = QtWidgets.QWidget()
    ui = Ui_voorkeurenpagina()
    ui.setupUi(voorkeurenpagina)
    voorkeurenpagina.show()
    sys.exit(app.exec())
