# Form implementation generated from reading ui file 'woordstudie.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Woordstudie(object):
    def setupUi(self, Woordstudie):
        Woordstudie.setObjectName("Woordstudie")
        Woordstudie.resize(850, 850)
        Woordstudie.setMinimumSize(QtCore.QSize(850, 850))
        Woordstudie.setMaximumSize(QtCore.QSize(850, 850))
        Woordstudie.setStyleSheet("QWidget {\n"
"    background-image: url(\"C:/Users/harri/Desktop/Nederlands app/images/arkaplan_resmi.webp\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"}\n"
"/* Başlık Frame\'i */\n"
"QFrame {\n"
"    background: transparent; /* Şeffaf bırak */\n"
"    border: none;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #f0f8ff; /* Açık mavi tonunda arka plan */\n"
"    border: 2px solid #4682b4; /* Hafif koyu mavi çerçeve */\n"
"    border-radius: 8px; /* Köşeleri yuvarlak yap */\n"
"    padding: 6px; /* İçeride boşluk bırak */\n"
"    font-size: 14px;\n"
"    color: #333; /* Yazı rengi */\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"    background: transparent; \n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #31857F;\n"
"}\n"
"\n"
"/* Kullanıcı Girişi Frame\'i */\n"
"QFrame#inputFrame {\n"
"    background: transparent; \n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #f0f5f9;\n"
"    border: 2px solid #5EAAA8;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 16px;\n"
"    color: #333;\n"
"}\n"
"\n"
"/* Butonların Bulunduğu Frame */\n"
"QFrame#progressFrame {\n"
"    background: transparent;\n"
"}\n"
"QPushButton {\n"
"    background-color: #5EAAA8; /* Normal buton rengi */\n"
"    color: #F4D03F; /* Sarımsı yazı rengi */\n"
"    border-radius: 10px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    padding: 8px 15px;\n"
"    font-size: 20px;\n"
"    border: 2px solid #31857F;\n"
"}\n"
"\n"
"/* Mouse ile üzerine gelince */\n"
"QPushButton:hover {\n"
"    background-color: #76C7C0; /* Daha açık yeşil */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Tıklayınca */\n"
"QPushButton:pressed {\n"
"    background-color: #EAF4F4; /* Açık renk */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Butonun şeffaf olmasını önlemek için */\n"
"QPushButton:!disabled {\n"
"    background: #5EAAA8; \n"
"}\n"
"")
        self.comboBox_verwanteVormen = QtWidgets.QComboBox(parent=Woordstudie)
        self.comboBox_verwanteVormen.setGeometry(QtCore.QRect(50, 300, 181, 31))
        self.comboBox_verwanteVormen.setObjectName("comboBox_verwanteVormen")
        self.comboBox_woordselecteer = QtWidgets.QComboBox(parent=Woordstudie)
        self.comboBox_woordselecteer.setGeometry(QtCore.QRect(50, 233, 181, 31))
        self.comboBox_woordselecteer.setObjectName("comboBox_woordselecteer")
        self.comboBox_woordtype = QtWidgets.QComboBox(parent=Woordstudie)
        self.comboBox_woordtype.setGeometry(QtCore.QRect(50, 163, 181, 31))
        self.comboBox_woordtype.setStyleSheet("")
        self.comboBox_woordtype.setCurrentText("")
        self.comboBox_woordtype.setObjectName("comboBox_woordtype")
        self.label_4 = QtWidgets.QLabel(parent=Woordstudie)
        self.label_4.setGeometry(QtCore.QRect(52, 277, 171, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(parent=Woordstudie)
        self.label_2.setGeometry(QtCore.QRect(50, 136, 181, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Woordstudie)
        self.label_3.setGeometry(QtCore.QRect(50, 211, 201, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_metinAra = QtWidgets.QLineEdit(parent=Woordstudie)
        self.lineEdit_metinAra.setGeometry(QtCore.QRect(290, 290, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_metinAra.setFont(font)
        self.lineEdit_metinAra.setText("")
        self.lineEdit_metinAra.setObjectName("lineEdit_metinAra")
        self.pushButton = QtWidgets.QPushButton(parent=Woordstudie)
        self.pushButton.setGeometry(QtCore.QRect(728, 290, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_duzenle = QtWidgets.QPushButton(parent=Woordstudie)
        self.pushButton_duzenle.setGeometry(QtCore.QRect(668, 356, 151, 51))
        self.pushButton_duzenle.setObjectName("pushButton_duzenle")
        self.pushButton_kaydet = QtWidgets.QPushButton(parent=Woordstudie)
        self.pushButton_kaydet.setGeometry(QtCore.QRect(279, 356, 151, 51))
        self.pushButton_kaydet.setObjectName("pushButton_kaydet")
        self.pushButton_sil = QtWidgets.QPushButton(parent=Woordstudie)
        self.pushButton_sil.setGeometry(QtCore.QRect(470, 356, 151, 51))
        self.pushButton_sil.setObjectName("pushButton_sil")
        self.label_5 = QtWidgets.QLabel(parent=Woordstudie)
        self.label_5.setGeometry(QtCore.QRect(290, 130, 121, 31))
        self.label_5.setObjectName("label_5")
        self.textEdit_aciklama = QtWidgets.QTextEdit(parent=Woordstudie)
        self.textEdit_aciklama.setGeometry(QtCore.QRect(280, 167, 531, 101))
        self.textEdit_aciklama.setStyleSheet("#textEdit_aciklama {\n"
"    background-color: #f0f5f9; /* Açık sarı tonu (tablodaki gibi) */\n"
"    border: 2px solid #5EAAA8; /* Çerçeve */\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"")
        self.textEdit_aciklama.setReadOnly(True)
        self.textEdit_aciklama.setObjectName("textEdit_aciklama")
        self.lineEdit_Nederlands = QtWidgets.QLineEdit(parent=Woordstudie)
        self.lineEdit_Nederlands.setGeometry(QtCore.QRect(40, 487, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_Nederlands.setFont(font)
        self.lineEdit_Nederlands.setText("")
        self.lineEdit_Nederlands.setObjectName("lineEdit_Nederlands")
        self.lineEdit_Turkce = QtWidgets.QLineEdit(parent=Woordstudie)
        self.lineEdit_Turkce.setGeometry(QtCore.QRect(40, 420, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_Turkce.setFont(font)
        self.lineEdit_Turkce.setStyleSheet("    background-color: #F0F8FF;  /* Açık mavi tonları */\n"
"    border: 2px solid #5EAAA8;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 16px;\n"
"    color: #333;")
        self.lineEdit_Turkce.setText("")
        self.lineEdit_Turkce.setObjectName("lineEdit_Turkce")
        self.tableWidget_zinnen = QtWidgets.QTableWidget(parent=Woordstudie)
        self.tableWidget_zinnen.setGeometry(QtCore.QRect(30, 550, 781, 291))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_zinnen.setFont(font)
        self.tableWidget_zinnen.setStyleSheet("background-color: rgb(246, 255, 205);")
        self.tableWidget_zinnen.setObjectName("tableWidget_zinnen")
        self.tableWidget_zinnen.setColumnCount(0)
        self.tableWidget_zinnen.setRowCount(0)
        self.label = QtWidgets.QLabel(parent=Woordstudie)
        self.label.setGeometry(QtCore.QRect(290, 60, 271, 41))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \"Comic Sans MS\"; /* Daha eğlenceli ve oyunumsu bir font */\n"
"    font-size: 25pt; /* Boyutu biraz daha artırdık, daha dikkat çekici olsun */\n"
"    font-weight: bold; /* Kalın yazı (eğlenceli duruşu koruyor) */\n"
"    color: #F57C00; /* Daha koyu turuncu ton (orijinal #FF9800’dan daha derin) */\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_Terug = QtWidgets.QPushButton(parent=Woordstudie)
        self.pushButton_Terug.setGeometry(QtCore.QRect(630, 10, 201, 41))
        self.pushButton_Terug.setStyleSheet("QPushButton {\n"
"    background-color: #5EAAA8; /* Normal buton rengi */\n"
"    color: #F4D03F; /* Sarımsı yazı rengi */\n"
"    border-radius: 10px;\n"
"    font-family: \"Comic Sans MS\";\n"
"    padding: 8px 15px;\n"
"    font-size: 15px;\n"
"    border: 2px solid #31857F;\n"
"}\n"
"\n"
"/* Mouse ile üzerine gelince */\n"
"QPushButton:hover {\n"
"    background-color: #76C7C0; /* Daha açık yeşil */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Tıklayınca */\n"
"QPushButton:pressed {\n"
"    background-color: #EAF4F4; /* Açık renk */\n"
"    border: 2px solid #5EAAA8;\n"
"}\n"
"\n"
"/* Butonun şeffaf olmasını önlemek için */\n"
"QPushButton:!disabled {\n"
"    background: #5EAAA8; \n"
"}\n"
"")
        self.pushButton_Terug.setObjectName("pushButton_Terug")

        self.retranslateUi(Woordstudie)
        QtCore.QMetaObject.connectSlotsByName(Woordstudie)

    def retranslateUi(self, Woordstudie):
        _translate = QtCore.QCoreApplication.translate
        Woordstudie.setWindowTitle(_translate("Woordstudie", "Woordstudie"))
        self.label_4.setText(_translate("Woordstudie", "Verwante vormen"))
        self.label_2.setText(_translate("Woordstudie", "Kies het woordtype"))
        self.label_3.setText(_translate("Woordstudie", "Selecteer een woord"))
        self.pushButton.setText(_translate("Woordstudie", "Zoek"))
        self.pushButton_duzenle.setText(_translate("Woordstudie", "Wijzigen"))
        self.pushButton_kaydet.setText(_translate("Woordstudie", "Opslaan"))
        self.pushButton_sil.setText(_translate("Woordstudie", "Verwijderen"))
        self.label_5.setText(_translate("Woordstudie", "Beschrijving"))
        self.lineEdit_Nederlands.setPlaceholderText(_translate("Woordstudie", "Voer een zin in het Nederlands in"))
        self.lineEdit_Turkce.setPlaceholderText(_translate("Woordstudie", "Voer een zin in het Turks in"))
        self.label.setText(_translate("Woordstudie", "Woordstudie"))
        self.pushButton_Terug.setText(_translate("Woordstudie", "Terug naar startpagina"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Woordstudie = QtWidgets.QWidget()
    ui = Ui_Woordstudie()
    ui.setupUi(Woordstudie)
    Woordstudie.show()
    sys.exit(app.exec())
