# Form implementation generated from reading ui file 'preference_menu_user.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Preference_menu_user(object):
    def setupUi(self, Preference_menu_user):
        Preference_menu_user.setObjectName("Preference_menu_user")
        Preference_menu_user.resize(1024, 860)
        Preference_menu_user.setMinimumSize(QtCore.QSize(1024, 860))
        Preference_menu_user.setMaximumSize(QtCore.QSize(1024, 860))
        Preference_menu_user.setStyleSheet("QWidget {\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"stop:0 #4D9E63, stop:1 #5A99D9);\n"
"\n"
"\n"
"}\n"
"QPushButton {\n"
"    background-color: #2196F3;\n"
"    border-radius: 16px;\n"
"    border: 2px solid #1976D2;\n"
"    padding: 10px 20px;\n"
"    font-size: 26px;\n"
"    color: white;\n"
"    box-shadow: 0 4px #1976D2;\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #42A5F5;\n"
"    box-shadow: 0 8px #1976D2;\n"
"    transform: scale(1.2);  /* Butonu büyüt */\n"
"    font-size: 32px; /* Yazıyı büyüt */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E88E5;\n"
"    box-shadow: 0 2px #1976D2;\n"
"    transform: scale(1.1); /* Basılınca biraz küçült */\n"
"    font-size: 30px; /* Yazıyı biraz küçült */\n"
"}\n"
"")
        self.pushButton_Exit_2 = QtWidgets.QPushButton(parent=Preference_menu_user)
        self.pushButton_Exit_2.setGeometry(QtCore.QRect(740, 740, 145, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_Exit_2.setFont(font)
        self.pushButton_Exit_2.setStyleSheet("QPushButton {\n"
"  background-color: #1565C0;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #1976D2;\n"
"    padding: 10px 20px;\n"
"    font-size: 22px;\n"
"    color: white;\n"
"    box-shadow: 0 4px #1976D2;\n"
"    transition: all 0.3s ease;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #42A5F5;\n"
"    box-shadow: 0 6px #1976D2;\n"
"    transform: translateY(-4px);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E88E5;\n"
"    box-shadow: 0 2px #1976D2;\n"
"    transform: translateY(2px);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/exit.png.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Exit_2.setIcon(icon)
        self.pushButton_Exit_2.setObjectName("pushButton_Exit_2")
        self.label = QtWidgets.QLabel(parent=Preference_menu_user)
        self.label.setGeometry(QtCore.QRect(-4, -10, 1031, 181))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QWidget {\n"
"    font: bold 32px \"Verdana\";\n"
"    color: #004080;\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"stop:0 #C2D9F0, stop:1 #85B1CF);\n"
"\n"
"    text-shadow: 2px 2px 3px #996600;\n"
"    border-radius: 16px;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_applications = QtWidgets.QPushButton(parent=Preference_menu_user)
        self.pushButton_applications.setGeometry(QtCore.QRect(140, 230, 271, 131))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_applications.setFont(font)
        self.pushButton_applications.setObjectName("pushButton_applications")
        self.pushButton_mentorMeeting = QtWidgets.QPushButton(parent=Preference_menu_user)
        self.pushButton_mentorMeeting.setGeometry(QtCore.QRect(360, 450, 331, 131))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_mentorMeeting.setFont(font)
        self.pushButton_mentorMeeting.setObjectName("pushButton_mentorMeeting")
        self.pushButton_interviews = QtWidgets.QPushButton(parent=Preference_menu_user)
        self.pushButton_interviews.setGeometry(QtCore.QRect(610, 230, 271, 131))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_interviews.setFont(font)
        self.pushButton_interviews.setObjectName("pushButton_interviews")

        self.retranslateUi(Preference_menu_user)
        QtCore.QMetaObject.connectSlotsByName(Preference_menu_user)

    def retranslateUi(self, Preference_menu_user):
        _translate = QtCore.QCoreApplication.translate
        Preference_menu_user.setWindowTitle(_translate("Preference_menu_user", "Preference Menu (User)"))
        self.pushButton_Exit_2.setText(_translate("Preference_menu_user", "Exit"))
        self.label.setText(_translate("Preference_menu_user", "PREFERENCE MENU"))
        self.pushButton_applications.setText(_translate("Preference_menu_user", "Applications"))
        self.pushButton_mentorMeeting.setText(_translate("Preference_menu_user", "Mentor Meeting"))
        self.pushButton_interviews.setText(_translate("Preference_menu_user", "Interviews"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Preference_menu_user = QtWidgets.QWidget()
    ui = Ui_Preference_menu_user()
    ui.setupUi(Preference_menu_user)
    Preference_menu_user.show()
    sys.exit(app.exec())
